package com.chris64233.numberporting.domain;

/**
 * 不可变事件类型，构成号码携转的完整时间线。
 */
public enum PortingEventType {
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_CANCELLED,
    APPLICATION_EXPIRED,
    APPLICATION_COMPLETED,
    SWITCH_STARTED,
    SWITCH_COMPLETED,
    SWITCH_FAILED,
    ROLLBACK_STARTED,
    ROLLBACK_COMPLETED,
    ROLLBACK_FAILED,
    AUTH_CODE_REVOKED,
    AUTH_CODE_EXPIRED
}
