package com.chris64233.numberporting.exception;

/**
 * 可向调用方解释的业务错误码。并发竞态的“失败方”会拿到明确、唯一的终态解释。
 */
public enum ErrorCode {
    NUMBER_NOT_FOUND,
    ACTIVE_APPLICATION_EXISTS,
    APPLICATION_NOT_FOUND,
    IDEMPOTENCY_MISMATCH,
    AUTH_CODE_NOT_FOUND,
    AUTH_CODE_ALREADY_USED,
    AUTH_CODE_EXPIRED,
    AUTH_CODE_REVOKED,
    AUTH_CODE_MISMATCH,
    ILLEGAL_TRANSITION,
    SWITCH_WINDOW_CLOSED,
    ROLLBACK_WINDOW_CLOSED,
    CONCURRENT_MODIFICATION,
    INVARIANT_VIOLATION,
    SWITCH_EXECUTION_FAILED,
    ROLLBACK_EXECUTION_FAILED,
    VALIDATION_ERROR
}
